version: "3.9"

services:

    api-comentario:
        image: franciscosoares1987/innovationcast-api-comentario:latest
        container_name: innovationcast-api-comentario
        build: 
            context: ../src
            dockerfile: ./Backend.Challenge.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
        ports:
            - "8080:80"
        depends_on:
            - db-postgres
            
    db-postgres:
        image: postgres
        container_name: innovationcast-db-postgres
        restart: always
        volumes:
            - ../data/postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
            
    pgadmin:
        image: dpage/pgadmin4
        container_name: innovationcast-pgadmin
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - "15432:80"
        depends_on:
            - db-postgres
